FROM node:20

# Create the working directory explicitly
RUN mkdir -p /opt/server
WORKDIR /opt/server

# Copy package.json and install dependencies
COPY package.json . 
RUN npm install

# Copy JS files
COPY *.js .

# Set environment variables
ENV MONGO="true" \
    MONGO_URL="mongodb://mongodb:27017/catalogue"

# Start the app
CMD ["node", "server.js"]
