FROM node:20
# Create the working directory explicitly
RUN mkdir -p /opt/server
WORKDIR /opt/server
# Copy package.json and install dependencies
COPY package.json . 
RUN npm install
# Copy JS files
COPY *.js .s
# Set environment variables
ENV MONGO="true" \
    REDIS_URL='redis://redis:6379' \
    MONGO_URL="mongodb://mongodb:27017/users"
# Start the app
CMD ["node", "server.js"]
